CREATE TABLE User
(
    id CHAR(20) NOT NULL,
    password CHAR(20) NOT NULL ,

    member_id BIGINT NOT NULL ,
    card_id CHAR(20) NOT NULL ,

    del INT DEFAULT 1,
    version INT DEFAULT 1,
    create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modify_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

DROP TABLE User;

CREATE TABLE Information
(
    id BIGINT AUTO_INCREMENT,
    user_id CHAR(20) NOT NULL ,

    name VARCHAR(50) NOT NULL ,
    sex CHAR(10) NOT NULL ,
    city VARCHAR(100) NOT NULL ,
    province VARCHAR(100) NOT NULL ,
    work VARCHAR(100) NOT NULL ,

    del INT DEFAULT 1,
    version INT DEFAULT 1,
    create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
    modify_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

DROP TABLE Information;

CREATE TABLE Points
(
    id BIGINT AUTO_INCREMENT,
    user_id CHAR(20) NOT NULL ,

    points BIGINT DEFAULT 0,

    del INT DEFAULT 1,
    version INT DEFAULT 1,
    create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modify_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

DROP TABLE Points;

CREATE TABLE Activity
(
    id BIGINT AUTO_INCREMENT,
    question_id BIGINT NOT NULL ,
    user_id CHAR(20) NOT NULL ,

    del INT DEFAULT 1,
    version INT DEFAULT 1,
    create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modify_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

DROP TABLE Activity;

CREATE TABLE Collect
(
    id BIGINT AUTO_INCREMENT,
    question_id Long NOT NULL ,
    user_id CHAR(20) NOT NULL ,
    del INT DEFAULT 1,
    version INT DEFAULT 1,
    create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modify_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

DROP TABLE Collect;

CREATE TABLE Forward
(
    id BIGINT AUTO_INCREMENT,
    question_id BIGINT ,
    user_id CHAR(20) NOT NULL ,
    del INT DEFAULT 1,
    version INT DEFAULT 1,
    create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modify_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

DROP TABLE Forward;

CREATE TABLE Blog
(
    id BIGINT AUTO_INCREMENT,
    content VARCHAR(100) NOT NULL ,
    photo1 VARCHAR(100),
    photo2 VARCHAR(100),
    photo3 VARCHAR(100),
    user_id CHAR(20) NOT NULL ,
    del INT DEFAULT 1,
    version INT DEFAULT 1,
    create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modify_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

DROP TABLE Blog;

CREATE TABLE BlogComment
(
    id BIGINT AUTO_INCREMENT,
    blog_id BIGINT,
    user_id CHAR(20) NOT NULL ,
    content VARCHAR(100) NOT NULL ,
    del INT DEFAULT 1,
    version INT DEFAULT 1,
    create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modify_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

DROP TABLE BlogComment;
