CREATE TABLE Card
(
    id CHAR(20) NOT NULL,
    money DOUBLE DEFAULT 0.00,

    del INT DEFAULT 1,
    version INT DEFAULT 1,
    create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modify_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

DROP TABLE Card;

CREATE TABLE Recharge
(
    id BIGINT AUTO_INCREMENT,
    money DOUBLE NOT NULL,
    card_id CHAR(20) NOT NULL ,
    del INT DEFAULT 1,
    version INT DEFAULT 1,
    create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modify_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

DROP TABLE Recharge;

CREATE TABLE Rate
(
    id BIGINT AUTO_INCREMENT,
    rate DOUBLE NOT NULL ,
    member_id BIGINT NOT NULL ,
    del INT DEFAULT 1,
    version INT DEFAULT 1,
    create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modify_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

DROP TABLE Rate;

CREATE TABLE Member
(
    id BIGINT AUTO_INCREMENT,
    name VARCHAR(20) NOT NULL ,
    content VARCHAR(20) NOT NULL ,

    priority BIGINT NOT NULL ,
    add_points BIGINT NOT NULL ,
    sub_points BIGINT NOT NULL ,

    del INT DEFAULT 1,
    version INT DEFAULT 1,
    create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modify_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

DROP TABLE Member;

