CREATE TABLE School
(
  id BIGINT AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL ,
  content VARCHAR(100),

  del INT DEFAULT 1,
  version INT DEFAULT 1,
  create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
  modify_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

DROP TABLE school;

CREATE TABLE Grade
(
    id BIGINT AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    school_id BIGINT NOT NULL ,
    content VARCHAR(100),

    del INT DEFAULT 1,
    version INT DEFAULT 1,
    create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
    modify_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

DROP TABLE grade;

CREATE TABLE CourseType
(
  id CHAR(20) NOT NULL ,
  name VARCHAR(100) NOT NULL ,

  del INT DEFAULT 1,
  version INT DEFAULT 1,
  create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
  modify_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

DROP TABLE coursetype;

CREATE TABLE Course
(
  id CHAR(20) NOT NULL,
  name VARCHAR(100) NOT NULL,
  content VARCHAR(100) NOT NULL ,

  grade_id BIGINT NOT NULL ,
  course_type_id CHAR(20),

  del INT DEFAULT 1,
  version INT DEFAULT 1,
  create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  modify_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

DROP TABLE course;

CREATE TABLE Question
(
      id BIGINT AUTO_INCREMENT,

      course_id CHAR(20) NOT NULL ,

      points BIGINT NOT NULL ,
      user_id CHAR(20) NOT NULL ,

      title VARCHAR(100) NOT NULL ,
      content VARCHAR(100) NOT NULL ,
      photo1 VARCHAR(100),
      photo2 VARCHAR(100),
      photo3 VARCHAR(100),

      del INT DEFAULT 1,
      version INT DEFAULT 1,
      create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      modify_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      PRIMARY KEY (id)
);

DROP TABLE Question;

CREATE TABLE Comment
(
    id BIGINT AUTO_INCREMENT,
    question_id BIGINT NOT NULL ,
    user_id CHAR(20) NOT NULL ,
    content VARCHAR(100) NOT NULL ,
    photo1 VARCHAR(100),
    photo2 VARCHAR(100),
    photo3 VARCHAR(100),
    del INT DEFAULT 1,
    version INT DEFAULT 1,
    create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modify_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

DROP TABLE comment;

CREATE TABLE Notice
(
    id BIGINT AUTO_INCREMENT ,
    course_id CHAR(20) NOT NULL ,
    content VARCHAR(100) NOT NULL ,
    photo1 VARCHAR(100),
    photo2 VARCHAR(100),
    photo3 VARCHAR(100),
    del INT DEFAULT 1,
    version INT DEFAULT 1,
    create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modify_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

DROP TABLE notice;

CREATE TABLE Winner
(
    id BIGINT AUTO_INCREMENT,
    question_id BIGINT NOT NULL ,
    user_id CHAR(60) NOT NULL ,
    del INT DEFAULT 1,
    version INT DEFAULT 1,
    create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modify_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

DROP TABLE winner;






